"""Synthetic NovaTech catalogue. All requirement text is original demo wording — Prototype / Demonstration Mapping,
not copied from any standard."""

DEPARTMENTS = ["Engineering", "IT", "Security", "HR", "Finance", "Legal", "Sales", "Marketing", "Operations",
               "Procurement", "Customer Success", "Executive"]

# code-number: (name, domain, department, frequency_days, criticality, automation)
CONTROLS = {
    1: ("Information Security Policy Approval", "Governance", "Legal", 365, 3, "manual"),
    2: ("Security Roles & Responsibilities", "Governance", "Executive", 365, 3, "manual"),
    3: ("Segregation of Duties Review", "Governance", "Finance", 180, 4, "manual"),
    4: ("Asset Inventory Maintenance", "Asset Management", "IT", 90, 3, "automated"),
    5: ("Acceptable Use Acknowledgement", "People", "HR", 365, 2, "automated"),
    6: ("Information Classification Labelling", "Data Protection", "Legal", 180, 3, "manual"),
    7: ("Media Handling & Disposal", "Asset Management", "IT", 180, 2, "manual"),
    8: ("Data Encryption at Rest", "Cryptography", "Engineering", 180, 5, "automated"),
    9: ("Encryption Key Rotation", "Cryptography", "Security", 90, 3, "manual"),
    10: ("TLS Configuration Standard", "Cryptography", "Engineering", 180, 4, "automated"),
    11: ("Joiner Access Provisioning", "Access Control", "IT", 90, 4, "automated"),
    12: ("Mover Access Modification", "Access Control", "IT", 90, 3, "manual"),
    13: ("Leaver Access Revocation", "Access Control", "HR", 30, 5, "automated"),
    14: ("Multi-Factor Authentication Enforcement", "Access Control", "Security", 90, 5, "automated"),
    15: ("Password Policy Enforcement", "Access Control", "IT", 180, 3, "automated"),
    16: ("Service Account Management", "Access Control", "Engineering", 90, 4, "manual"),
    17: ("Quarterly User Access Review", "Access Control", "IT", 90, 4, "manual"),
    18: ("Privileged Access Review", "Access Control", "Security", 90, 5, "manual"),
    19: ("Remote Access Controls", "Access Control", "IT", 180, 4, "automated"),
    20: ("Secure Configuration Baselines", "Operations Security", "IT", 90, 4, "automated"),
    21: ("Vulnerability Scanning", "Operations Security", "Security", 30, 5, "automated"),
    22: ("Patch Management SLA", "Operations Security", "IT", 30, 4, "automated"),
    23: ("Endpoint Protection Coverage", "Operations Security", "IT", 30, 4, "automated"),
    24: ("Backup Restoration Test", "Resilience", "IT", 90, 5, "manual"),
    25: ("Backup Job Monitoring", "Resilience", "IT", 30, 4, "automated"),
    26: ("Capacity Monitoring", "Operations", "Operations", 90, 2, "automated"),
    27: ("Logging & Monitoring Coverage", "Monitoring", "Security", 90, 4, "automated"),
    28: ("Log Retention", "Monitoring", "Security", 180, 3, "automated"),
    29: ("Security Event Alert Triage", "Monitoring", "Security", 30, 4, "manual"),
    30: ("Clock Synchronisation", "Operations", "IT", 365, 2, "automated"),
    31: ("Vendor Security Assessment", "Supplier Management", "Procurement", 180, 4, "manual"),
    32: ("Vendor Contract Security Clauses", "Supplier Management", "Legal", 365, 3, "manual"),
    33: ("Cloud Service Provider Review", "Supplier Management", "Engineering", 365, 4, "manual"),
    34: ("Supplier Offboarding", "Supplier Management", "Procurement", 180, 2, "manual"),
    35: ("Change Management Approval", "Change Management", "Engineering", 90, 4, "automated"),
    36: ("Emergency Change Review", "Change Management", "Engineering", 90, 3, "manual"),
    37: ("Code Review Enforcement", "Secure Development", "Engineering", 90, 4, "automated"),
    38: ("Secure SDLC Training", "Secure Development", "Engineering", 365, 3, "automated"),
    39: ("Dependency Vulnerability Scanning", "Secure Development", "Engineering", 30, 4, "automated"),
    40: ("Production Deployment Controls", "Secure Development", "Engineering", 90, 4, "automated"),
    41: ("Incident Response Plan Maintenance", "Incident Management", "Security", 365, 4, "manual"),
    42: ("Incident Response Test", "Incident Management", "Security", 180, 5, "manual"),
    43: ("Incident Post-Mortem Reviews", "Incident Management", "Security", 90, 3, "manual"),
    44: ("Breach Notification Procedure", "Incident Management", "Legal", 365, 4, "manual"),
    45: ("Business Continuity Plan", "Resilience", "Operations", 365, 4, "manual"),
    46: ("Disaster Recovery Test", "Resilience", "IT", 365, 5, "manual"),
    47: ("Physical Access Controls", "Physical Security", "Operations", 90, 3, "automated"),
    48: ("Visitor Management", "Physical Security", "Operations", 180, 2, "manual"),
    49: ("Clean Desk Checks", "Physical Security", "Operations", 180, 1, "manual"),
    50: ("Background Verification", "People", "HR", 180, 4, "manual"),
    51: ("Employment Contract Confidentiality", "People", "HR", 365, 3, "manual"),
    52: ("Disciplinary Process", "People", "HR", 365, 2, "manual"),
    53: ("Privacy Notice Maintenance", "Privacy", "Legal", 365, 3, "manual"),
    54: ("Consent Management", "Privacy", "Marketing", 90, 4, "automated"),
    55: ("Data Retention & Disposal", "Privacy", "Legal", 180, 4, "manual"),
    56: ("Data Subject Request Handling", "Privacy", "Customer Success", 90, 4, "manual"),
    57: ("Personal Data Inventory", "Privacy", "Legal", 180, 3, "manual"),
    58: ("Cross-Border Transfer Assessment", "Privacy", "Legal", 365, 3, "manual"),
    59: ("Data Protection Impact Assessment", "Privacy", "Legal", 180, 3, "manual"),
    60: ("Network Segmentation", "Network Security", "IT", 180, 4, "automated"),
    61: ("Firewall Rule Review", "Network Security", "Security", 90, 4, "manual"),
    62: ("Wireless Security", "Network Security", "IT", 365, 2, "automated"),
    63: ("Security Awareness Training", "People", "HR", 365, 3, "automated"),
    64: ("Phishing Simulation", "People", "Security", 90, 3, "automated"),
    65: ("Risk Assessment", "Governance", "Executive", 365, 4, "manual"),
    66: ("Risk Treatment Tracking", "Governance", "Legal", 90, 3, "manual"),
    67: ("Management Review", "Governance", "Executive", 365, 3, "manual"),
    68: ("Internal Audit Programme", "Governance", "Finance", 365, 3, "manual"),
    69: ("Compliance Obligation Register", "Governance", "Legal", 180, 3, "manual"),
    70: ("Threat Intelligence Review", "Monitoring", "Security", 90, 2, "manual"),
    71: ("Data Loss Prevention Monitoring", "Data Protection", "Security", 90, 4, "automated"),
    72: ("Database Access Logging", "Monitoring", "Engineering", 90, 4, "automated"),
    73: ("Customer Data Segregation", "Data Protection", "Engineering", 180, 5, "automated"),
    74: ("API Security Testing", "Secure Development", "Engineering", 180, 4, "automated"),
    75: ("Penetration Testing", "Operations Security", "Security", 365, 5, "manual"),
    76: ("Mobile Device Management", "Endpoint", "IT", 90, 3, "automated"),
    77: ("Financial System Access Review", "Access Control", "Finance", 90, 4, "manual"),
    78: ("Sales CRM Access Review", "Access Control", "Sales", 180, 3, "manual"),
    79: ("Marketing Data Handling", "Privacy", "Marketing", 180, 2, "manual"),
    80: ("Customer Support Data Access", "Access Control", "Customer Success", 180, 3, "manual"),
    81: ("Procurement Approval Workflow", "Governance", "Procurement", 180, 2, "automated"),
    82: ("Expense Fraud Monitoring", "Governance", "Finance", 90, 2, "automated"),
    83: ("Secrets Management", "Cryptography", "Engineering", 90, 5, "automated"),
    84: ("Container Image Hardening", "Operations Security", "Engineering", 90, 4, "automated"),
}

# framework -> [(code, title, category, [control numbers])]  — synthetic wording
REQUIREMENTS = {
    "ISO27001": [
        ("ISO-5.01", "Information security policies are defined and approved", "Governance", [1]),
        ("ISO-5.02", "Security roles and responsibilities are assigned", "Governance", [2]),
        ("ISO-5.03", "Conflicting duties are segregated", "Governance", [3]),
        ("ISO-5.09", "Information assets are inventoried", "Asset Management", [4]),
        ("ISO-5.10", "Acceptable use of information is defined", "People", [5]),
        ("ISO-5.12", "Information is classified by sensitivity", "Data Protection", [6]),
        ("ISO-5.15", "Access to information is controlled", "Access Control", [11, 12, 13]),
        ("ISO-5.16", "Identities are managed through their lifecycle", "Access Control", [11]),
        ("ISO-5.17", "Authentication information is protected", "Access Control", [15]),
        ("ISO-5.18", "Access rights are periodically reviewed and adjusted", "Access Control", [17]),
        ("ISO-5.19", "Supplier security risks are assessed", "Supplier Management", [31]),
        ("ISO-5.20", "Supplier agreements address security", "Supplier Management", [32]),
        ("ISO-5.23", "Use of cloud services is secured", "Supplier Management", [33]),
        ("ISO-5.24", "Incident management is planned and prepared", "Incident Management", [41]),
        ("ISO-5.26", "Security incidents are responded to", "Incident Management", [42, 43]),
        ("ISO-5.29", "Security is maintained during disruption", "Resilience", [45]),
        ("ISO-5.30", "ICT readiness supports continuity", "Resilience", [46]),
        ("ISO-5.31", "Legal and regulatory obligations are identified", "Governance", [69]),
        ("ISO-5.33", "Records are protected and retained appropriately", "Privacy", [55]),
        ("ISO-5.34", "Personal data is protected", "Privacy", [53, 57]),
        ("ISO-5.35", "Security is independently reviewed", "Governance", [68]),
        ("ISO-6.01", "Personnel are screened before joining", "People", [50]),
        ("ISO-6.02", "Employment terms include security duties", "People", [51]),
        ("ISO-6.03", "Personnel receive security awareness training", "People", [63, 64]),
        ("ISO-6.04", "A disciplinary process exists for violations", "People", [52]),
        ("ISO-6.05", "Security duties continue after termination", "People", [13]),
        ("ISO-7.02", "Physical entry is controlled", "Physical Security", [47]),
        ("ISO-7.07", "Clear desk and screen rules are applied", "Physical Security", [49]),
        ("ISO-7.10", "Storage media is handled securely", "Asset Management", [7]),
        ("ISO-8.02", "Privileged access rights are restricted and reviewed", "Access Control", [18]),
        ("ISO-8.05", "Secure authentication is enforced", "Access Control", [14]),
        ("ISO-8.07", "Systems are protected against malware", "Operations Security", [23]),
        ("ISO-8.08", "Technical vulnerabilities are managed", "Operations Security", [21, 22]),
        ("ISO-8.09", "Configurations are managed", "Operations Security", [20]),
        ("ISO-8.13", "Information is backed up and restorable", "Resilience", [24, 25]),
        ("ISO-8.15", "Activity logs are produced and protected", "Monitoring", [27, 28]),
        ("ISO-8.16", "Systems are monitored for anomalous behaviour", "Monitoring", [29]),
        ("ISO-8.20", "Networks are secured", "Network Security", [60, 61]),
        ("ISO-8.24", "Cryptography is used effectively", "Cryptography", [8, 10]),
        ("ISO-8.25", "Development follows a secure lifecycle", "Secure Development", [37, 38, 74]),
        ("ISO-8.32", "Changes are controlled", "Change Management", [35, 36]),
        ("ISO-8.11", "Sensitive data is masked in non-production use", "Data Protection", []),
    ],
    "SOC2": [
        ("SOC-CC1.1", "Commitment to integrity and ethical values", "Governance", [51]),
        ("SOC-CC1.3", "Organisational structure and reporting lines", "Governance", [2]),
        ("SOC-CC2.1", "Quality information supports internal control", "Governance", [69]),
        ("SOC-CC3.1", "Risk objectives are specified", "Governance", [65]),
        ("SOC-CC3.2", "Risks to objectives are identified", "Governance", [65, 66]),
        ("SOC-CC4.1", "Controls are monitored for operation", "Governance", [68, 67]),
        ("SOC-CC5.1", "Control activities mitigate risk", "Governance", [3]),
        ("SOC-CC6.1", "Logical access is restricted to authorised users", "Access Control", [14, 16, 83]),
        ("SOC-CC6.2", "Users are registered and authorised before access", "Access Control", [11]),
        ("SOC-CC6.3", "Access is modified and removed promptly", "Access Control", [12, 13, 17]),
        ("SOC-CC6.4", "Physical access to facilities is restricted", "Physical Security", [47, 48]),
        ("SOC-CC6.5", "Cryptographic keys are managed", "Cryptography", [9, 83]),
        ("SOC-CC6.6", "External threats at boundaries are managed", "Network Security", [60, 61]),
        ("SOC-CC6.7", "Data in transmission is protected", "Cryptography", [10]),
        ("SOC-CC6.8", "Malicious software is prevented or detected", "Operations Security", [23, 84]),
        ("SOC-CC7.1", "Configuration changes are monitored", "Operations Security", [20, 84]),
        ("SOC-CC7.2", "Anomalies are monitored", "Monitoring", [27, 29, 70]),
        ("SOC-CC7.3", "Security events are evaluated", "Monitoring", [29]),
        ("SOC-CC7.4", "Incidents are responded to", "Incident Management", [41, 42]),
        ("SOC-CC7.5", "Recovery from incidents is performed", "Incident Management", [43]),
        ("SOC-CC8.1", "Changes are authorised and tested", "Change Management", [35, 40]),
        ("SOC-CC9.1", "Business disruption risk is mitigated", "Resilience", [45]),
        ("SOC-CC9.2", "Vendor and partner risk is managed", "Supplier Management", [31, 33]),
        ("SOC-A1.1", "Processing capacity is monitored", "Operations", [26]),
        ("SOC-A1.2", "Backups and recovery infrastructure are maintained", "Resilience", [24, 25, 46]),
        ("SOC-C1.1", "Confidential information is identified and protected", "Data Protection", [71, 73]),
        ("SOC-C1.2", "Confidential information is disposed of securely", "Data Protection", [7, 55]),
        ("SOC-PI1.1", "Processing integrity objectives are monitored", "Governance", [82]),
    ],
    "NIST_CSF": [
        ("NIST-GV.OC-03", "Legal and regulatory requirements are understood", "Govern", [69]),
        ("NIST-GV.RM-01", "Risk management objectives are established", "Govern", [65]),
        ("NIST-GV.RR-02", "Cybersecurity roles are established", "Govern", [2]),
        ("NIST-GV.SC-07", "Supplier risks are assessed and monitored", "Govern", [31, 34]),
        ("NIST-GV.PO-01", "Cybersecurity policy is established", "Govern", [1]),
        ("NIST-ID.AM-01", "Hardware inventories are maintained", "Identify", [4, 76]),
        ("NIST-ID.AM-07", "Data inventories are maintained", "Identify", [57]),
        ("NIST-ID.RA-01", "Asset vulnerabilities are identified", "Identify", [21, 75]),
        ("NIST-ID.RA-08", "Vulnerability disclosures are processed", "Identify", [39]),
        ("NIST-PR.AA-01", "Identities and credentials are managed", "Protect", [11, 16]),
        ("NIST-PR.AA-03", "Users and services are authenticated", "Protect", [14, 15]),
        ("NIST-PR.AA-05", "Access permissions are defined and reviewed", "Protect", [17, 18, 77, 78, 80]),
        ("NIST-PR.AT-01", "Personnel receive awareness training", "Protect", [63, 64]),
        ("NIST-PR.DS-01", "Data at rest is protected", "Protect", [8, 73]),
        ("NIST-PR.DS-02", "Data in transit is protected", "Protect", [10]),
        ("NIST-PR.DS-11", "Backups are created, protected and tested", "Protect", [24, 25]),
        ("NIST-PR.PS-01", "Configuration management practices are applied", "Protect", [20, 84]),
        ("NIST-PR.PS-02", "Software is maintained commensurate with risk", "Protect", [22]),
        ("NIST-PR.PS-04", "Log records are generated for monitoring", "Protect", [27, 28, 72]),
        ("NIST-PR.IR-01", "Networks are protected from unauthorised use", "Protect", [60, 61, 62]),
        ("NIST-DE.CM-01", "Networks are monitored for adverse events", "Detect", [29, 70]),
        ("NIST-DE.AE-02", "Adverse events are analysed", "Detect", [29]),
        ("NIST-RS.MA-01", "Incident response plan is executed", "Respond", [41, 42]),
        ("NIST-RC.RP-01", "Recovery plan is executed", "Recover", [45, 46]),
    ],
    "DPDP": [
        ("DPDP-01", "Data principals receive clear notice", "Notice", [53]),
        ("DPDP-02", "Consent is free, specific and withdrawable", "Consent", [54]),
        ("DPDP-03", "Personal data is used only for stated purposes", "Purpose", [79]),
        ("DPDP-04", "Personal data is kept accurate and complete", "Quality", [56]),
        ("DPDP-05", "Personal data is erased when no longer needed", "Retention", [55]),
        ("DPDP-06", "Reasonable security safeguards prevent breaches", "Security", [71, 73]),
        ("DPDP-07", "Personal data breaches are intimated", "Breach", [44]),
        ("DPDP-08", "Data principal rights requests are honoured", "Rights", [56]),
        ("DPDP-09", "Grievances are redressed in time", "Rights", [56]),
        ("DPDP-10", "Verifiable consent is obtained for children's data", "Consent", [54]),
        ("DPDP-11", "Cross-border transfers are assessed", "Transfer", [58]),
        ("DPDP-12", "Periodic impact assessments are conducted", "Assessment", [59]),
    ],
}

FRAMEWORKS = {
    "ISO27001": ("ISO/IEC 27001-style Information Security Controls", "2022-style"),
    "SOC2": ("SOC 2-style Trust Services Controls", "2017-style"),
    "NIST_CSF": ("NIST CSF 2.0-style Cybersecurity Functions", "2.0-style"),
    "DPDP": ("India DPDP-style Privacy Controls", "2023-style"),
}

POLICIES = [
    ("POL-001", "Information Security Policy", "Legal", "3.0", 365, [1, 2]),
    ("POL-002", "Access Control Policy", "IT", "2.4", 365, [17, 18, 11, 13]),
    ("POL-003", "Acceptable Use Policy", "HR", "2.1", 365, [5]),
    ("POL-004", "Data Retention & Disposal Policy", "Legal", "1.3", 365, [55]),
    ("POL-005", "Incident Response Policy", "Security", "3.1", 365, [41, 42]),
    ("POL-006", "Vendor Management Policy", "Procurement", "2.0", 365, [31, 32]),
    ("POL-007", "Backup & Recovery Policy", "IT", "1.8", 365, [24, 25]),
    ("POL-008", "Cryptography & Key Management Standard", "Security", "1.5", 365, [8, 9, 83]),
    ("POL-009", "Secure Development Policy", "Engineering", "2.2", 365, [37, 40]),
    ("POL-010", "Privacy & Personal Data Policy", "Legal", "2.0", 365, [53, 54, 56]),
    ("POL-011", "HR Security Policy", "HR", "1.6", 365, [50, 51]),
    ("POL-012", "Business Continuity Policy", "Operations", "1.9", 365, [45, 46]),
    ("POL-013", "Change Management Policy", "Engineering", "2.3", 365, [35, 36]),
    ("POL-014", "Physical Security Policy", "Operations", "1.4", 365, [47, 48]),
]

FIRST = ["Aarav", "Aditi", "Akash", "Ananya", "Anil", "Anjali", "Arun", "Bhavna", "Chetan", "Deepa", "Dev", "Divya",
         "Farhan", "Gaurav", "Geeta", "Harish", "Isha", "Jatin", "Karan", "Kiran", "Lakshmi", "Manish", "Meera", "Mohit",
         "Nandini", "Naveen", "Neha", "Nikhil", "Pooja", "Pranav", "Rajesh", "Ramya", "Ravi", "Riya", "Rohan", "Sanjay",
         "Shreya", "Siddharth", "Simran", "Suresh", "Swati", "Tanvi", "Tarun", "Uday", "Varun", "Vidya", "Yash", "Zoya",
         "Daniel", "Emma", "Grace", "Liam", "Maya", "Noah", "Olivia", "Sofia"]
LAST = ["Agarwal", "Bhat", "Chopra", "Das", "Gupta", "Iyer", "Joshi", "Kapoor", "Khan", "Kulkarni", "Menon", "Mishra",
        "Nair", "Pillai", "Rao", "Reddy", "Saxena", "Shah", "Sharma", "Singh", "Srinivasan", "Thomas", "Varma", "Yadav",
        "Fernandes", "D'Souza", "Banerjee", "Chatterjee", "Patel", "Krishnan"]

PERSONAS = [
    # email, name, role, department, title
    ("priya.raman@novatech.demo", "Priya Raman", "COMPLIANCE_OFFICER", "Legal", "Head of Compliance"),
    ("arjun.mehta@novatech.demo", "Arjun Mehta", "AUDITOR", "Finance", "Internal Auditor"),
    ("kavya.nair@novatech.demo", "Kavya Nair", "SECURITY_ADMIN", "Security", "Security Operations Lead"),
    ("rahul.verma@novatech.demo", "Rahul Verma", "CONTROL_OWNER", "IT", "IT Access Manager"),
    ("sneha.iyer@novatech.demo", "Sneha Iyer", "EMPLOYEE", "Marketing", "Marketing Analyst"),
    ("vikram.sethi@novatech.demo", "Vikram Sethi", "EXECUTIVE", "Executive", "Chief Operating Officer"),
]
DEMO_PASSWORD = "NovaTech-Demo-2026"
